version: '3.8'
services:
  chroma:
    image: chromadb/chroma:latest
    container_name: omnix-chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - omnix-network
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local

networks:
  omnix-network:
    driver: bridge